
version: "3"

services:

  site_2:
    image: php:7.2.2-apache
    volumes:
              - ./www/:/var/www/html/
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: www.synclabsolutions.com

    container_name: synclab_site

networks:
  default:
    external:
      name: nginx-proxy
