# ./docker-compose.yml

version: '3.5'

services:
  mysql_1:
    image: mysql:5.7
    container_name: mysql_1
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"

  web:
    image: thilinaperera/nginx-php-server
    container_name: php_nginx_web_1
    depends_on:
      - mysql_1
    volumes:
      - ./www:/var/www/html
      - ./config:/etc/nginx/custom-sites
    ports:
      - "80:80"
    links:
      - mysql_1

    # stdin_open: true
    # tty: true

volumes:
  db_data:

