#
#version: "3"
#
#  services:
#      web:
#        image: php:7.2.2-apache
#
#        volumes:
#          - ./www/:/var/www/html/
#        expose:
#          - 80
#        restart: always
#        environment:
#          VIRTUAL_HOST: www.vikum.xyz
#
#        container_name: php_web_1
#
#
#    networks:
#      default:
#        external:
#          name: nginx-proxy
#
##===================================

version: "3"

services:
  db_node_domain:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD
    container_name: wordpress_db

  wordpress:
    depends_on:
      - db_node_domain
    image: php:7.2.2-apache
    volumes:
              - ./www/:/var/www/html/
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: www.vikum.xyz
      WORDPRESS_DB_HOST: db_node_domain:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: PASSWORD
    container_name: wordpress
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
